version: '3'
services:
  mpv:
    image: youtube-mpv-server
    build: 
      context: youtube-mpv-server
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    ipc: host
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - $HOME/.config/mpv:/root/.config/mpv
      - $HOME/.cache/mpv:/root/.cache/mpv
      - $HOME/.Xauthority:/root/.Xauthority
